### ISSUE TITLE
Identifiant sql

### ISSUE THREAD

**Issue by Jean-seb11** [nricheton/jeedom-docker-optimized#1]
Bonjour, 

Je viens d'installer votre docker sur mon qnap.
Et lorsque je fait le 1er lancement, je me confronte a l'identification de la base sql 
(Comme vu par mail)
la base ne semble pas avoir été créée.

Merci pour l'aide

**Comment by nricheton** [comment]
Bonjour, 

Avez-vous bien lancé le conteneur jeedom-mysql ? 
si la base est vide, pouvez-vous effacer le conteneur ET les données et recommencer ? 

```
docker stop jeedom-mysql
docker volume rm jeedom-mysql
```

puis recommencer selon le README

**Comment by Jean-seb11** [comment]
Désolé mais je suis novice en docker.

Pour préciser, j’ai un jeedom V4 sur rpm3 fonctionnel que je voudrais transférer sur mon NAS via Docker

 

Du coup j’installe ton docker …

Petite question la base SQL est intégré a ton docker ou il faut le rajouter ?

 

Jean-Sébastien Pointcheval

 

De : Nicolas Richeton <notifications@github.com> 
Envoyé : samedi 4 avril 2020 14:31
À : nricheton/jeedom-docker-optimized <jeedom-docker-optimized@noreply.github.com>
Cc : Jean-seb11 <js.pointcheval@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [nricheton/jeedom-docker-optimized] Identifiant sql (#1)

 

Bonjour,

Avez-vous bien lancé le conteneur jeedom-mysql ?
si la base est vide, pouvez-vous effacer le conteneur ET les données et recommencer ?

docker stop jeedom-mysql
 
docker volume rm jeedom-mysql
 

puis recommencer selon le README

**Comment by nricheton** [comment]
Il y a 2 conteneurs différents, comme sur l'image Jeedom officiel :
 - 1 pour la base (conteneur standard mariadb)
 - 1 pour Jeedom 

Il faut lancer les 2 conteneurs séparément. Les 2 lignes de commande sont sur le readme.

Je vais écrire quelques instructions concernant la migration depuis une autre instance sur le readme. N'hésitez pas à compléter via des pull requests.

**Comment by Jean-seb11** [comment]
Ok merci,

 

Bon je comprends pas tout , 

Mais je pense que ça fonctionne pas car je cherche à installer ca sur un NAS QNAP via containerStation

 

Et que tes commandes sont à envoyer sur une machine linux

 

Jean-Sébastien Pointcheval

 

De : Nicolas Richeton <notifications@github.com> 
Envoyé : samedi 4 avril 2020 15:19
À : nricheton/jeedom-docker-optimized <jeedom-docker-optimized@noreply.github.com>
Cc : Jean-seb11 <js.pointcheval@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [nricheton/jeedom-docker-optimized] Identifiant sql (#1)

 

Il y a 2 conteneurs différents, comme sur l'image Jeedom officiel :

*	1 pour la base (conteneur standard mariadb)
*	1 pour Jeedom

Il faut lancer les 2 conteneurs séparément. Les 2 lignes de commande sont sur le readme.

Je vais écrire quelques instructions concernant la migration depuis une autre instance sur le readme. N'hésitez pas à compléter via des pull requests.

**Comment by nricheton** [comment]
Tu peux utiliser un client Mysql pour recharger le dump sans ligne de commande.

Exemples : https://mariadb.com/kb/en/graphical-and-enhanced-clients/
