### ISSUE TITLE
Support Raspberry Pi ?

### ISSUE THREAD

**Issue by KaKi87** [nricheton/jeedom-docker-optimized#2]
Bonjour,

Vous avez déprécié votre image [nricheton/jeedom-rpi](https://hub.docker.com/r/nricheton/jeedom-rpi) en faveur de [nricheton/jeedom-optimized](https://hub.docker.com/r/nricheton/jeedom-optimized), mais les tags sur cette dernière indique qu'il n'y a de versions que pour l'architecture `amd64`. Qu'en est-il donc du support pour Raspberry Pi, dont l'architecture est `armv7l` ?

Merci.

**Comment by nricheton** [comment]
Bonjour, 

L'image est cross-compilée pour arm, mais bizarrement, elle reste taguée amd64. 
Le tag **nricheton/jeedom-optimized:rpi-latest** fonctionne très bien sur raspberry. 

Voir le readme pour les tags disponibles.
